#caffeine缓存配置
caffeine:
  specs:
    defaultCache:
      timeToLiveInMinutes: 1440
      maxSize: 100000

#Redis缓存配置
redis:
  # standalone or cluster
  connection:
    type: standalone #单机
  standalone:
    host: ${REDIS_HOST:118.126.89.231}
    port: ${REDIS_PORT:6379}
    useDefaultClientConfig: ${REDIS_USE_DEFAULT_CLIENT_CONFIG:true}
    clientName: ${REDIS_CLIENT_NAME:standalone}
    connectTimeout: ${REDIS_CLIENT_CONNECT_TIMEOUT:30000}
    readTimeout: ${REDIS_CLIENT_READ_TIMEOUT:60000}
    usePoolConfig: ${REDIS_CLIENT_USE_POOL_CONFIG:false}
  cluster: #Redis集群配置
    # 集群节点配置值
    nodes: ${REDIS_NODES:}
    max-redirects: ${REDIS_MAX_REDIRECTS:12}
    useDefaultPoolConfig: ${REDIS_USE_DEFAULT_POOL_CONFIG:true}
  # db index
  db: ${REDIS_DB:0}
  # db password
  password: ${REDIS_PASSWORD:xdpGACL}
  # pool config
  pool_config:
    maxTotal: ${REDIS_POOL_CONFIG_MAX_TOTAL:128}
    maxIdle: ${REDIS_POOL_CONFIG_MAX_IDLE:128}
    minIdle: ${REDIS_POOL_CONFIG_MIN_IDLE:16}
    testOnBorrow: ${REDIS_POOL_CONFIG_TEST_ON_BORROW:true}
    testOnReturn: ${REDIS_POOL_CONFIG_TEST_ON_RETURN:true}
    testWhileIdle: ${REDIS_POOL_CONFIG_TEST_WHILE_IDLE:true}
    minEvictableMs: ${REDIS_POOL_CONFIG_MIN_EVICTABLE_MS:60000}
    evictionRunsMs: ${REDIS_POOL_CONFIG_EVICTION_RUNS_MS:30000}
    maxWaitMills: ${REDIS_POOL_CONFIG_MAX_WAIT_MS:60000}
    numberTestsPerEvictionRun: ${REDIS_POOL_CONFIG_NUMBER_TESTS_PER_EVICTION_RUN:3}
    blockWhenExhausted: ${REDIS_POOL_CONFIG_BLOCK_WHEN_EXHAUSTED:true}

#magic4j开发平台的相关配置统一以magic4j为前缀
magic4j:
  storage:
    local:
      fileSavePath: C:/data/magic4j/uploadFilesManager #上传文件本地文件保存目录
      fileUrlPathPattern: /uploadFile/*   #上传到本地服务器的文件的访问映射
  idempotent:
    authorization: idempotentToken # 幂等性Token请求头

#FastDFS配置
fdfs:
  enabled: true #启用
  trackerServers: 118.126.89.231:22122
  httpServer: http://file.itgacl.com

##################################################################################
# JSch 连接Linux服务器配置(使用JSch将上传的静态文件统一上传到远程Linux服务器) #
##################################################################################
jsch:
  ssh2:
    enabled: true #启用
    server:
      ip: 118.126.89.231 #服务器IP地址
      userName: root #服务器登录用户名
      password: xdp52@@LYX #服务器登录密码
      workPath: /data/uploadFilesManager #服务器工作目录(上传文件的保存目录)
      port: 22 #服务器SSH连接端口号
      domain: http://file.itgacl.com/uploadFile #文件服务器IP(域名，配合nginx)
##################################################################################

#云存储配置
#腾讯COS云存储配置
tencent:
  cos:
    enabled: true #启用
    appId: 1256200601
    secretId: AKIDSfgdKOjqJmcz71RZRAk5BBwgAB1p8A3h
    secretKey: 51h7GVYLrYrsgoeLo2pQ6YijS1KPCDqD
    bucketName: magic4j-1256200601
    region: ap-guangzhou #广州 （中国）
    rootPath: magic4j #文件保存根目录
    #domain: https://magic4j-1256200601.cos.ap-guangzhou.myqcloud.com #腾讯云cos提供的访问Bucket里面的文件的默认域名
    domain: http://cosfile.itgacl.com #cos存储文件的自定义访问域名，需要在阿里云控制台后台域名解析将cosfile.itgacl.com这个二级域名CNAME到magic4j-1256200601.cos.ap-guangzhou.myqcloud.com

#阿里云OSS云存储配置
aliyun:
  oss:
    enabled: true #启用
    accessKeyId: LTAI4G864rPigxELF92CUzBw #访问密钥
    accessKeySecret: XW8LwDpC9sAiTsfi2twrVzzSLzhmHi #访问密钥
    bucketName: magic4j #存储空间，存储空间是用户用于存储对象（Object）的容器，所有的对象都必须隶属于某个存储空间
    rootPath: magic4j
    endPoint: oss-cn-shenzhen.aliyuncs.com #表示OSS对外服务的访问域名，oss-accelerate.aliyuncs.com（传输加速域名（全地域上传下载加速））
    #domain: https://magic4j.oss-cn-shenzhen.aliyuncs.com 阿里云oss提供的访问Bucket里面的文件的默认域名
    domain: http://ossfile.itgacl.com #oss存储文件的自定义访问域名，需要在阿里云控制台后台域名解析将ossfile.itgacl.com这个二级域名CNAME到magic4j.oss-cn-shenzhen.aliyuncs.com

#七牛KODO云存储配置
qiniu:
  kodo:
    enabled: true #启用
    accessKey: emASy1O_k08IXqU9xn1JfN__XFgnb4MZMNGYEdOg
    secretKey: A3ub0nuF1aN4QxNATxsawT4-S5XC284UaM8ZFEW5
    bucketName: magic4j
    rootPath: magic4j
    domain: http://kodofile.itgacl.com #kodo存储的文件的自定义访问域名，需要在阿里云控制台后台域名解析将kodofile.itgacl.com这个二级域名CNAME到kodofile-itgacl-com-idvbhh9.qiniudns.com

#邮件发送配置
spring:
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 290603672@qq.com #QQ邮箱
    password: aybnwmcdkoizbgdb #客户端授权码
    protocol: smtp #发送邮件协议
    properties.mail.smtp.auth: true
    properties.mail.smtp.port: 465 #端口号465
    properties.mail.display.sendmail: magic4j(孤傲苍狼) #可以任意
    properties.mail.display.sendname: magic4j Email #可以任意
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
    from: 290603672@qq.com #与上面的username保持一致